const MAJOR_COLOR_NAMES = [
    "WHITE", "RED", "BLACK", "YELLOW", "VIOLET"
];
const MINOR_COLOR_NAMES = [
	"BLUE", "ORANGE", "GREEN", "BROWN", "SLATE"
];
module.exports = {MAJOR_COLOR_NAMES, MINOR_COLOR_NAMES}
